version: '3'
services:
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   ports:
  #     - '6500:5432'
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   env_file:
  #     - ./.env
  node-server:
    restart: always
    build: .
    ports:
      - '4001:4001'
volumes:
  postgres: